<a href="https://colab.research.google.com/github/notnsas/cautious-eureka/blob/main/Tugas%20Tehnik%20permodelan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd
import usaddress

In [2]:

# Set the path to the file you'd like to load
file_path_1 = "credit_card_fraud_dataset.csv"
file_path_2 = "Customer_DF (1).csv"
file_path_2_2 = "cust_transaction_details (1).csv"
file_path_3_test = "fraudTest.csv"
file_path_3_train = "fraudTrain.csv"

# Load the latest version
df1 = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "bhadramohit/credit-card-fraud-detection",
  file_path_1,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df2 = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "aryanrastogi7767/ecommerce-fraud-data",
  file_path_2,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df2_2 = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "aryanrastogi7767/ecommerce-fraud-data",
  file_path_2_2,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df3_train = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "kartik2112/fraud-detection",
  file_path_3_train,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df3_test = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "kartik2112/fraud-detection",
  file_path_3_test,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records for df1:", df1.head())
print("First 5 records for df2:", df2.head())
print("First 5 records for df3_train:", df3_train.head())
print("First 5 records for df3_test:", df3_test.head())

/tmp/ipython-input-1669517003.py:9: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df1 = kagglehub.load_dataset(

Using Colab cache for faster access to the 'credit-card-fraud-detection' dataset.

/tmp/ipython-input-1669517003.py:19: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df2 = kagglehub.load_dataset(

Using Colab cache for faster access to the 'ecommerce-fraud-data' dataset.

/tmp/ipython-input-1669517003.py:29: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df2_2 = kagglehub.load_dataset(

Using Colab cache for faster access to the 'ecommerce-fraud-data' dataset.

/tmp/ipython-input-1669517003.py:39: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df3_train = kagglehub.load_dataset(

Using Colab cache for faster access to the 'fraud-detection' dataset.

/tmp/ipython-input-1669517003.py:49: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df3_test = kagglehub.load_dataset(

Using Colab cache for faster access to the 'fraud-detection' dataset.
First 5 records for df1:    TransactionID             TransactionDate   Amount  MerchantID  \
0              1  2024-04-03 14:15:35.462794  4189.27         688
1              2  2024-03-19 13:20:35.462824  2659.71         109
2              3  2024-01-08 10:08:35.462834   784.00         394
3              4  2024-04-13 23:50:35.462850  3514.40         944
4              5  2024-07-12 18:51:35.462858   369.07         475

  TransactionType      Location  IsFraud
0          refund   San Antonio        0
1          refund        Dallas        0
2        purchase      New York        0
3        purchase  Philadelphia        0
4        purchase       Phoenix        0
First 5 records for df2:    Unnamed: 0              customerEmail       customerPhone  \
0           0     josephhoward@yahoo.com        400-108-5415
1           1     evansjeffery@yahoo.com      1-788-091-7546
2           2  andersonwilliam@yahoo.com        024.420.0375
3           3      rubenjuarez@yahoo.com  670.664.8168x94985
4           4           uchen@malone.com      1-981-877-0870

         customerDevice                        customerIPAddress  \
0  yyeiaxpltf82440jnb3v                             8.129.104.40
1  r0jpm7xaeqqa3kr6mzum                          219.173.211.202
2  4m7h5ipl1shyavt6vv2r  67b7:3db8:67e0:3bea:b9d0:90c1:2b60:b9f0
3  slovx60t0i558may4ks0  95de:8565:5a66:792c:26e0:6cfb:7d87:11af
4  j0pd24k5h8dl2fqu0cz4                           196.89.235.192

                              customerBillingAddress  No_Transactions  \
0            5493 Jones Islands\nBrownside, CA 51896                2
1  356 Elizabeth Inlet Suite 120\nPort Joshuabury...                3
2     8478 Sean Ridges Apt. 441\nDavisberg, PR 72250                5
3  7769 Elizabeth Bridge Apt. 343\nNortonstad, FM...                3
4  148 Russell Lodge Apt. 445\nPort Jenniferside,...                7

   No_Orders  No_Payments  Fraud
0          2            1  False
1          3            7   True
2          3            2  False
3          3            1  False
4          7            6   True
First 5 records for df3_train:    Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2019-01-01 00:00:18  2703186189652095
1           1   2019-01-01 00:00:44      630423337322
2           2   2019-01-01 00:00:51    38859492057661
3           3   2019-01-01 00:01:16  3534093764340240
4           4   2019-01-01 00:03:06   375534208663984

                             merchant       category     amt      first  \
0          fraud_Rippin, Kub and Mann       misc_net    4.97   Jennifer
1     fraud_Heller, Gutmann and Zieme    grocery_pos  107.23  Stephanie
2                fraud_Lind-Buckridge  entertainment  220.11     Edward
3  fraud_Kutch, Hermiston and Farrell  gas_transport   45.00     Jeremy
4                 fraud_Keeling-Crist       misc_pos   41.96      Tyler

      last gender                        street  ...      lat      long  \
0    Banks      F                561 Perry Cove  ...  36.0788  -81.1781
1     Gill      F  43039 Riley Greens Suite 393  ...  48.8878 -118.2105
2  Sanchez      M      594 White Dale Suite 530  ...  42.1808 -112.2620
3    White      M   9443 Cynthia Court Apt. 038  ...  46.2306 -112.1138
4   Garcia      M              408 Bradley Rest  ...  38.4207  -79.4629

   city_pop                                job         dob  \
0      3495          Psychologist, counselling  1988-03-09
1       149  Special educational needs teacher  1978-06-21
2      4154        Nature conservation officer  1962-01-19
3      1939                    Patent attorney  1967-01-12
4        99     Dance movement psychotherapist  1986-03-28

                          trans_num   unix_time  merch_lat  merch_long  \
0  0b242abb623afc578575680df30655b9  1325376018  36.011293  -82.048315
1  1f76529f8574734946361c461b024d99  1325376044  49.159047 -118.186462
2  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704 -112.154481
3  6b849c168bdad6f867558c3793159a81  1325376076  47.034331 -112.561071
4  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999  -78.632459

   is_fraud
0         0
1         0
2         0
3         0
4         0

[5 rows x 23 columns]
First 5 records for df3_test:    Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2020-06-21 12:14:25  2291163933867244
1           1   2020-06-21 12:14:33  3573030041201292
2           2   2020-06-21 12:14:53  3598215285024754
3           3   2020-06-21 12:15:15  3591919803438423
4           4   2020-06-21 12:15:17  3526826139003047

                               merchant        category    amt   first  \
0                 fraud_Kirlin and Sons   personal_care   2.86    Jeff
1                  fraud_Sporer-Keebler   personal_care  29.84  Joanne
2  fraud_Swaniawski, Nitzsche and Welch  health_fitness  41.28  Ashley
3                     fraud_Haley Group        misc_pos  60.05   Brian
4                 fraud_Johnston-Casper          travel   3.19  Nathan

       last gender                       street  ...      lat      long  \
0   Elliott      M            351 Darlene Green  ...  33.9659  -80.9355
1  Williams      F             3638 Marsh Union  ...  40.3207 -110.4360
2     Lopez      F         9333 Valentine Point  ...  40.6729  -73.5365
3  Williams      M  32941 Krystal Mill Apt. 552  ...  28.5697  -80.8191
4    Massey      M     5783 Evan Roads Apt. 465  ...  44.2529  -85.0170

   city_pop                     job         dob  \
0    333497     Mechanical engineer  1968-03-19
1       302  Sales professional, IT  1990-01-17
2     34496       Librarian, public  1970-10-21
3     54767            Set designer  1987-07-25
4      1126      Furniture designer  1955-07-06

                          trans_num   unix_time  merch_lat  merch_long  \
0  2da90c7d74bd46a0caf3777415b3ebd3  1371816865  33.986391  -81.200714
1  324cc204407e99f51b0d6ca0055005e7  1371816873  39.450498 -109.960431
2  c81755dbbbea9d5c77f094348a7579be  1371816893  40.495810  -74.196111
3  2159175b9efe66dc301f149d3d5abf8c  1371816915  28.812398  -80.883061
4  57ff021bd3f328f8738bb535c302a31b  1371816917  44.959148  -85.884734

   is_fraud
0         0
1         0
2         0
3         0
4         0

[5 rows x 23 columns]

In [3]:
# Menggabungkan train dan test df3, karena nanti akan kita pisah lagi untuk semua 3 dataset yg digabung
df3 = pd.concat([df3_test, df3_train])
df3

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1296670,2020-06-21 12:12:08,30263540414123,fraud_Reichel Inc,entertainment,15.56,Erik,Patterson,M,162 Jessica Row Apt. 072,...,37.7175,-112.4777,258,Geoscientist,1961-11-24,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0
1296671,1296671,2020-06-21 12:12:19,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,Jeffrey,White,M,8617 Holmes Terrace Suite 651,...,39.2667,-77.5101,100,"Production assistant, television",1979-12-11,278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0
1296672,1296672,2020-06-21 12:12:32,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,Christopher,Castaneda,M,1632 Cohen Drive Suite 639,...,32.9396,-105.8189,899,Naval architect,1967-08-30,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0
1296673,1296673,2020-06-21 12:13:36,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Joseph,Murray,M,42933 Ryan Underpass,...,43.3526,-102.5411,1126,Volunteer coordinator,1980-08-18,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0
1296674,1296674,2020-06-21 12:13:37,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Jeffrey,Smith,M,135 Joseph Mountains,...,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0

In [4]:
# Agar data tidak terpotong
pd.set_option('display.max_colwidth', None)

# Membuat dataframe list
dataframe_list = [df1, df2, df2_2, df3]

# Liat data teratas
for index, data in enumerate(dataframe_list):
  print(f"Dataframe ke {index+1}")
  display(data.head(15))

Dataframe ke 1

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0
5,6,2024-08-30 01:52:35.462867,3086.22,302,purchase,New York,0
6,7,2024-01-02 11:31:35.462875,1466.90,902,refund,Philadelphia,0
7,8,2024-05-12 12:25:35.462885,917.21,266,purchase,New York,0
8,9,2023-11-16 02:20:35.462894,1625.73,32,refund,Chicago,0
9,10,2023-10-24 06:51:35.462901,662.07,193,purchase,Dallas,0
10,11,2024-08-10 17:08:35.462908,3895.94,349,refund,San Antonio,0
11,12,2024-08-27 16:03:35.462915,944.94,359,purchase,San Jose,0
12,13,2024-08-31 02:38:35.462922,2855.69,219,refund,New York,0
13,14,2023-11-12 13:30:35.462928,4313.82,617,refund,San Jose,0
14,15,2024-07-13 09:02:35.462935,4599.06,529,refund,Philadelphia,0

Dataframe ke 2

,Unnamed: 0,customerEmail,customerPhone,customerDevice,customerIPAddress,customerBillingAddress,No_Transactions,No_Orders,No_Payments,Fraud
0,0,josephhoward@yahoo.com,400-108-5415,yyeiaxpltf82440jnb3v,8.129.104.40,"5493 Jones Islands\nBrownside, CA 51896",2,2,1,False
1,1,evansjeffery@yahoo.com,1-788-091-7546,r0jpm7xaeqqa3kr6mzum,219.173.211.202,"356 Elizabeth Inlet Suite 120\nPort Joshuabury, NM 37681",3,3,7,True
2,2,andersonwilliam@yahoo.com,024.420.0375,4m7h5ipl1shyavt6vv2r,67b7:3db8:67e0:3bea:b9d0:90c1:2b60:b9f0,"8478 Sean Ridges Apt. 441\nDavisberg, PR 72250",5,3,2,False
3,3,rubenjuarez@yahoo.com,670.664.8168x94985,slovx60t0i558may4ks0,95de:8565:5a66:792c:26e0:6cfb:7d87:11af,"7769 Elizabeth Bridge Apt. 343\nNortonstad, FM 51359",3,3,1,False
4,4,uchen@malone.com,1-981-877-0870,j0pd24k5h8dl2fqu0cz4,196.89.235.192,"148 Russell Lodge Apt. 445\nPort Jenniferside, TN 60556-0871",7,7,6,True
5,5,robinsoncynthia@dunn.com,+65(5)8997489788,hbww39m1wenbq4ymjhsx,43.166.163.164,"65233 Hutchinson Mountains\nMartinezside, OR 75588",1,1,2,True
6,6,samuel15@saunders-rhodes.com,05045239487,up7afvce5v0omniqlevq,33.67.35.30,"3960 Emily Fort\nStaceytown, AR 21817-3325",2,1,2,True
7,7,johnlowery@gmail.com,044-642-9860,rjb0adai34izqvys4938,212.144.68.190,"484 Pamela Pass\nLake Jessicaview, WI 12942-9074",6,5,2,True
8,8,jameslandry@rodriguez.com,1-885-168-1310x338,yz4l2bgbvzra5eb5qcan,c899:ff67:6864:4365:def3:3023:655f:5181,USNS Price\nFPO AE 14661,5,2,1,False
9,9,ubranch@rivera-parker.info,(772)964-8162x6310,6mpx027neyz6sh04n3ue,86.16.65.228,"6974 Robertson Common Apt. 902\nPort Juanside, ID 80590-9633",0,0,1,True
10,10,bowenwilliam@yahoo.com,(128)248-4091x37789,qmntgod0numz62gzbla7,231.91.253.19,"27061 Wright Forks\nCraigland, MN 59915",6,5,1,True
11,11,ksummers@hotmail.com,1-023-275-4692,2ngkzu1idwxintmxwmgn,184.97.57.11,"46383 Matthew Track Apt. 220\nRomanburgh, DC 95125",7,5,4,False
12,12,christineklein@wright-boyd.org,897-464-6425x941,j8cp1uydkuyza2eo0mir,4304:521a:e1c3:766b:21f3:ac3:4ab2:5a2,"67636 Renee Islands Suite 307\nTeresaview, ND 09042",4,4,3,False
13,13,meganwalters@chavez.com,(522)133-8741x643,qsxqbn6qjxkni7f813qn,98.229.160.246,"7541 Olson Glens\nBallshire, IL 29415",4,2,1,False
14,14,caleb94@sutton.info,07452086668,lixwrlvcr4g5ht600dk9,2efe:240f:cc33:306:8e47:b8d5:b466:f12a,"813 Miller Lakes\nLake Christina, SD 29778-1298",5,5,2,False

Dataframe ke 3

,Unnamed: 0,customerEmail,transactionId,orderId,paymentMethodId,paymentMethodRegistrationFailure,paymentMethodType,paymentMethodProvider,transactionAmount,transactionFailed,orderState
0,0,josephhoward@yahoo.com,a9lcj51r,vjbdvd,wt07xm68b,1,card,JCB 16 digit,18,0,pending
1,1,josephhoward@yahoo.com,y4wcv03i,yp6x27,wt07xm68b,1,card,JCB 16 digit,26,0,fulfilled
2,2,evansjeffery@yahoo.com,5mi94sfw,nlghpa,41ug157xz,0,bitcoin,American Express,45,0,fulfilled
3,3,evansjeffery@yahoo.com,br8ba1nu,uw0eeb,41ug157xz,0,bitcoin,American Express,23,0,fulfilled
4,4,evansjeffery@yahoo.com,a33145ss,bn44oh,y3xp697jx,1,bitcoin,VISA 16 digit,43,1,fulfilled
5,5,andersonwilliam@yahoo.com,q3lyvbza,yk34y2,8pneoi03z,0,card,JCB 16 digit,33,0,failed
6,6,andersonwilliam@yahoo.com,3alf9irw,28v6b0,8pneoi03z,0,card,JCB 16 digit,24,1,fulfilled
7,7,andersonwilliam@yahoo.com,69w9wymx,28v6b0,8pneoi03z,0,card,JCB 16 digit,24,0,fulfilled
8,8,andersonwilliam@yahoo.com,pegqc4ud,itnk8y,dluy3jka0,0,card,Discover,25,1,fulfilled
9,9,andersonwilliam@yahoo.com,uo3slwh7,itnk8y,8pneoi03z,0,card,JCB 16 digit,25,0,fulfilled
10,10,rubenjuarez@yahoo.com,vx4cjc27,fbz9ep,pdxjdwui4,0,card,Voyager,34,0,fulfilled
11,11,rubenjuarez@yahoo.com,yiay9b0n,7odnn6,pdxjdwui4,0,card,Voyager,26,0,fulfilled
12,12,rubenjuarez@yahoo.com,sn3v0ql2,audx7o,pdxjdwui4,0,card,Voyager,25,0,fulfilled
13,13,uchen@malone.com,q8j3dgni,56h7iw,olr4zf09x,0,card,VISA 13 digit,71,0,fulfilled
14,14,uchen@malone.com,xjulqy8x,kowj1v,gehl28i8u,0,card,JCB 16 digit,66,1,fulfilled

Dataframe ke 4

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
5,5,2020-06-21 12:15:37,30407675418785,fraud_Daugherty LLC,kids_pets,19.55,Danielle,Evans,F,76752 David Lodge Apt. 064,...,42.1939,-76.7361,520,Psychotherapist,1991-10-13,798db04aaceb4febd084f1a7c404da93,1371816937,41.747157,-77.584197,0
6,6,2020-06-21 12:15:44,213180742685905,fraud_Romaguera Ltd,health_fitness,133.93,Kayla,Sutton,F,010 Weaver Land,...,40.5070,-123.9743,1139,"Therapist, occupational",1951-01-15,17003d7ce534440eadb10c4750e020e5,1371816944,41.499458,-124.888729,0
7,7,2020-06-21 12:15:50,3589289942931264,fraud_Reichel LLC,personal_care,10.37,Paula,Estrada,F,350 Stacy Glens,...,43.7557,-97.5936,343,"Development worker, international aid",1972-03-05,8be473af4f05fc6146ea55ace73e7ca2,1371816950,44.495498,-97.728453,0
8,8,2020-06-21 12:16:10,3596357274378601,"fraud_Goyette, Howell and Collier",shopping_pos,4.37,David,Everett,M,4138 David Fall,...,41.0001,-78.2357,3688,Advice worker,1973-05-27,71a1da150d1ce510193d7622e08e784e,1371816970,41.546067,-78.120238,0
9,9,2020-06-21 12:16:11,3546897637165774,fraud_Kilback Group,food_dining,66.54,Kayla,Obrien,F,7921 Robert Port Suite 343,...,31.6591,-96.8094,263,Barrister,1956-05-30,a7915132c7c4240996ba03a47f81e3bd,1371816971,31.782919,-96.366185,0
10,10,2020-06-21 12:16:20,2242542703101233,"fraud_Feil, Hilpert and Koss",food_dining,7.01,Samuel,Jenkins,M,43235 Mckenzie Views Apt. 837,...,38.4921,-85.4524,564,Pensions consultant,1996-04-10,3b8e4d02d9e1a3bf97cf449eb0317f2c,1371816980,38.977546,-84.727994,0
11,11,2020-06-21 12:16:47,571465035400,fraud_Gottlieb Group,kids_pets,42.40,Louis,Fisher,M,45654 Hess Rest,...,43.0048,-108.8964,1645,Freight forwarder,1976-02-26,fa3071565d94fb286cb0ed398c6d61d3,1371817007,42.687774,-108.670054,0
12,12,2020-06-21 12:17:21,6593250708747804,fraud_Connelly-Carter,home,2.91,Melissa,Meza,F,244 Abbott Parkway,...,26.7383,-80.2760,26551,Paramedic,1977-01-04,a21cb82e7d8fdbf4062f15c9422a4ca6,1371817041,26.078460,-80.569932,0
13,13,2020-06-21 12:18:27,4988304376504,fraud_Bechtelar-Rippin,food_dining,7.93,William,Thompson,M,977 Rita Grove Apt. 000,...,41.4575,-74.1659,2258,Building surveyor,1937-03-17,d0d2b5cca5ae19e0a07dc7ef5d51e59e,1371817107,40.711680,-73.668384,0
14,14,2020-06-21 12:18:37,6011504998544485,fraud_Lubowitz-Walter,kids_pets,2.91,Ashley,Whitney,F,4038 Smith Avenue,...,32.5104,-86.8138,1089,Materials engineer,1971-11-02,61dca41a9728ea5fd6db99efd59768f8,1371817117,32.721131,-87.253846,0

In [5]:
# Fungsi untuk menunjukan kolom
def print_col():
  col_name = []
  col_name.append(df1.columns.to_list())
  col_name.append(df2.columns.to_list())
  col_name.append(df3.columns.to_list())
  print("Columns for df1:", col_name[0])
  print("Columns for df2:", col_name[1])
  print("Columns for df3:", col_name[2])
print_col()

Columns for df1: ['TransactionID', 'TransactionDate', 'Amount', 'MerchantID', 'TransactionType', 'Location', 'IsFraud']
Columns for df2: ['Unnamed: 0', 'customerEmail', 'customerPhone', 'customerDevice', 'customerIPAddress', 'customerBillingAddress', 'No_Transactions', 'No_Orders', 'No_Payments', 'Fraud']
Columns for df3: ['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat', 'merch_long', 'is_fraud']

In [6]:
# Aggregasi transaction amount
df2_agg = df2_2.groupby('customerEmail', as_index=False)['transactionAmount'].sum()

# join
df2 = df2.merge(df2_agg[['transactionAmount', 'customerEmail']], on='customerEmail', how='left')
df2

,Unnamed: 0,customerEmail,customerPhone,customerDevice,customerIPAddress,customerBillingAddress,No_Transactions,No_Orders,No_Payments,Fraud,transactionAmount
0,0,josephhoward@yahoo.com,400-108-5415,yyeiaxpltf82440jnb3v,8.129.104.40,"5493 Jones Islands\nBrownside, CA 51896",2,2,1,False,44.0
1,1,evansjeffery@yahoo.com,1-788-091-7546,r0jpm7xaeqqa3kr6mzum,219.173.211.202,"356 Elizabeth Inlet Suite 120\nPort Joshuabury, NM 37681",3,3,7,True,111.0
2,2,andersonwilliam@yahoo.com,024.420.0375,4m7h5ipl1shyavt6vv2r,67b7:3db8:67e0:3bea:b9d0:90c1:2b60:b9f0,"8478 Sean Ridges Apt. 441\nDavisberg, PR 72250",5,3,2,False,131.0
3,3,rubenjuarez@yahoo.com,670.664.8168x94985,slovx60t0i558may4ks0,95de:8565:5a66:792c:26e0:6cfb:7d87:11af,"7769 Elizabeth Bridge Apt. 343\nNortonstad, FM 51359",3,3,1,False,85.0
4,4,uchen@malone.com,1-981-877-0870,j0pd24k5h8dl2fqu0cz4,196.89.235.192,"148 Russell Lodge Apt. 445\nPort Jenniferside, TN 60556-0871",7,7,6,True,411.0
...,...,...,...,...,...,...,...,...,...,...,...
163,163,mitchellvickie@brewer-jones.com,313-124-3836x3528,ecu7ezz0ue67v3fce1o3,181.90.104.120,"829 Ramirez Dam Suite 648\nGatesview, OR 55669-8691",3,3,1,True,126.0
164,164,sbrown@hughes.biz,(250)632-6631x02499,xgv918sclaz40qlp2fee,16.166.2.0,"9472 Pacheco Islands Suite 940\nDrewburgh, AZ 04238",6,5,3,True,149.0
165,165,johnlowery@gmail.com,635.676.0955x524,969zz9zdj8z4gns4sx5p,f82c:811f:8a02:e2d6:79b:fcaa:42de:570b,"548 Bryant Inlet\nVeronicaside, OK 00522",4,4,2,True,1033.0
166,166,ethompson@jackson-sanders.com,962.300.2250,navessqcnmc9csfjn5cj,203.246.172.244,"16953 Jennifer Springs\nKathybury, IL 02095-3215",8,6,6,True,378.0
167,167,dawn05@tucker-brown.com,(089)703-7360x8848,lu4fgcug8dr0dwbcuui1,132.132.95.33,"130 Kimberly Junctions\nEricmouth, KS 59756-2919",7,5,4,False,176.0

In [7]:
# Kolom sesudah part 1 dan part 2 dataset dari df2 digabungkan
print_col()

Columns for df1: ['TransactionID', 'TransactionDate', 'Amount', 'MerchantID', 'TransactionType', 'Location', 'IsFraud']
Columns for df2: ['Unnamed: 0', 'customerEmail', 'customerPhone', 'customerDevice', 'customerIPAddress', 'customerBillingAddress', 'No_Transactions', 'No_Orders', 'No_Payments', 'Fraud', 'transactionAmount']
Columns for df3: ['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat', 'merch_long', 'is_fraud']

In [8]:
# Fungsi untuk mengekstrak address kolom
def parse_address(addr):
  dict_addr = usaddress.tag(addr)
  return dict_addr

In [9]:
# Mengubah kolom dataframe ke-2 agar dapat mengekstrak fitur penting di kolom address
df_new = df2['customerBillingAddress'].apply(parse_address).apply(pd.Series)[0].apply(pd.Series)
df2 = pd.concat([df2, df_new], axis=1)
df2.columns

Index(['Unnamed: 0', 'customerEmail', 'customerPhone', 'customerDevice',
       'customerIPAddress', 'customerBillingAddress', 'No_Transactions',
       'No_Orders', 'No_Payments', 'Fraud', 'transactionAmount',
       'AddressNumber', 'StreetName', 'StreetNamePostType', 'PlaceName',
       'StateName', 'ZipCode', 'OccupancyType', 'OccupancyIdentifier',
       'Recipient', 'USPSBoxType', 'USPSBoxID', 'StreetNamePostDirectional',
       'USPSBoxGroupType', 'USPSBoxGroupID'],
      dtype='object')

In [10]:
# Kolom kode statename sebelum diubah
df2['StateName']

0      CA
1      NM
2      PR
3      FM
4      TN
       ..
163    OR
164    AZ
165    OK
166    IL
167    KS
Name: StateName, Length: 168, dtype: object

In [11]:
# Mengubah code state dari us ke nama lengkapnya
us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "Virgin Islands, U.S.": "VI",
}
us_reverse = {value: key for key, value in us_state_to_abbrev.items()}

def state_transform(x):
  us_reverse[x]

df2['StateName'] = df2['StateName'].map(us_reverse)
df3['state'] = df3['state'].map(us_reverse)

In [12]:
# Hasil dari mengubah kode state us
df2['StateName']

0       California
1       New Mexico
2      Puerto Rico
3              NaN
4        Tennessee
          ...
163         Oregon
164        Arizona
165       Oklahoma
166       Illinois
167         Kansas
Name: StateName, Length: 168, dtype: object

In [13]:
df3['state']

0          South Carolina
1                    Utah
2                New York
3                 Florida
4                Michigan
                ...
1296670              Utah
1296671          Maryland
1296672        New Mexico
1296673      South Dakota
1296674           Montana
Name: state, Length: 1852394, dtype: object

In [14]:
print_col()

Columns for df1: ['TransactionID', 'TransactionDate', 'Amount', 'MerchantID', 'TransactionType', 'Location', 'IsFraud']
Columns for df2: ['Unnamed: 0', 'customerEmail', 'customerPhone', 'customerDevice', 'customerIPAddress', 'customerBillingAddress', 'No_Transactions', 'No_Orders', 'No_Payments', 'Fraud', 'transactionAmount', 'AddressNumber', 'StreetName', 'StreetNamePostType', 'PlaceName', 'StateName', 'ZipCode', 'OccupancyType', 'OccupancyIdentifier', 'Recipient', 'USPSBoxType', 'USPSBoxID', 'StreetNamePostDirectional', 'USPSBoxGroupType', 'USPSBoxGroupID']
Columns for df3: ['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat', 'merch_long', 'is_fraud']

In [15]:
# Mapping kolom berbeda → nama kolom seragam
rename_maps = [
    {'Amount': 'amount', 'Location': 'location', 'IsFraud': 'is_fraud'},
    {'transactionAmount': 'amount', 'StateName': 'location', 'Fraud': 'is_fraud'},
    {'amt': 'amount', 'state': 'location', 'Fraudulent': 'is_fraud'}
]

# Rename tiap DataFrame sesuai mapping
df1 = df1.rename(columns=rename_maps[0])
df2 = df2.rename(columns=rename_maps[1])
df3 = df3.rename(columns=rename_maps[2])
# Gabungkan ketiganya
# pd.concat([df1, df2, df3], ignore_index=True)

In [16]:
print_col()

Columns for df1: ['TransactionID', 'TransactionDate', 'amount', 'MerchantID', 'TransactionType', 'location', 'is_fraud']
Columns for df2: ['Unnamed: 0', 'customerEmail', 'customerPhone', 'customerDevice', 'customerIPAddress', 'customerBillingAddress', 'No_Transactions', 'No_Orders', 'No_Payments', 'is_fraud', 'amount', 'AddressNumber', 'StreetName', 'StreetNamePostType', 'PlaceName', 'location', 'ZipCode', 'OccupancyType', 'OccupancyIdentifier', 'Recipient', 'USPSBoxType', 'USPSBoxID', 'StreetNamePostDirectional', 'USPSBoxGroupType', 'USPSBoxGroupID']
Columns for df3: ['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amount', 'first', 'last', 'gender', 'street', 'city', 'location', 'zip', 'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat', 'merch_long', 'is_fraud']

In [17]:
# Kolom yang ingin dipertahankan
keep_cols = ['amount', 'location', 'is_fraud']

# Drop semua kolom selain keep_cols untuk setiap df
dfs = [df1[keep_cols], df2[keep_cols], df3[keep_cols]]

# Gabungkan semuanya
df = pd.concat(dfs, ignore_index=True)

In [18]:
# Dataframe yang sudah digabung
df

          amount      location  is_fraud
0        4189.27   San Antonio         0
1        2659.71        Dallas         0
2         784.00      New York         0
3        3514.40  Philadelphia         0
4         369.07       Phoenix         0
...          ...           ...       ...
1952557    15.56          Utah         0
1952558    51.70      Maryland         0
1952559   105.93    New Mexico         0
1952560    74.90  South Dakota         0
1952561     4.30       Montana         0

[1952562 rows x 3 columns]

In [19]:
from datetime import date
from uuid import UUID, uuid4
from enum import Enum
from pydantic import BaseModel
from pandantic import Pandantic

# Membuat class fraud untuk validasi pake pydantics
class Fraud(BaseModel):
    amount: float
    location: str
    is_fraud: int

validator = Pandantic(schema=Fraud)

# DataFrame untuk mengecek apakah invalid
df_invalid = df
# Pengecekan
df_valid = validator.validate(dataframe=df_invalid, errors="skip")

In [20]:
# Drop nilai kosong
df_valid = df_valid.dropna()

In [21]:
# --- Imports ---
import pandas as pd
import numpy as np
from imblearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from imblearn.ensemble import BalancedRandomForestClassifier, RUSBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer
from joblib import dump
from imblearn.under_sampling import RandomUnderSampler
from imblearn.ensemble import BalancedBaggingClassifier
from sklearn.tree import DecisionTreeClassifier

# Memisah X dan y
X = df_valid.drop('is_fraud', axis=1)
y = df_valid['is_fraud']

# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2,
                                                      random_state=0, stratify=y)
numerical_cols = X.select_dtypes(include=np.number).columns
categorical_cols = X.select_dtypes(exclude=np.number).columns

# Numerik pipeline: imputer (mean) + scaler
numerical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

# Kategorikal pipeline: imputer (paling sering) + one-hot encoder
categorical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

# Gabungkan keduanya ke column transformer
preprocessor = ColumnTransformer(transformers=[
    ('num', numerical_pipeline, numerical_cols),
    ('cat', categorical_pipeline, categorical_cols)
])

# smt = SMOTE(random_state=42)
over = SMOTE(sampling_strategy=0.1)
# over = SMOTE()
under = RandomUnderSampler(sampling_strategy=0.5)

# --- Models ---
models = {
    "Random Forest Classifier": RandomForestClassifier(class_weight='balanced_subsample', random_state=42),
    "RUSBoost Classifier": RUSBoostClassifier(random_state=42),
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Gradient Boosting Classifier": GradientBoostingClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    min_samples_leaf=20,
    subsample=0.8,
    random_state=42
),
    "Balanced Random Forest Classifier": BalancedRandomForestClassifier(random_state=42),
}

# --- Train, evaluasi, dan simpan models ---
for name, model in models.items():
    pipeline = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('over', over),
        ('under', under),
        ('model', model)
    ])

    # Train model
    pipeline.fit(X_train, y_train)

    # Prediksi di test set
    y_pred = pipeline.predict(X_test)

    # Kalkulasi metriks
    acc = accuracy_score(y_test, y_pred)

    # Print hasil
    print(f"\n📊 {name}")
    print(f"Accuracy : {acc:.3f}")

    # Simpan model
    filename = f"{name.replace(' ', '_').lower()}.joblib"
    dump(pipeline, filename)
    print(f"Model ke simpan ke {filename}")

📊 Random Forest Classifier
Accuracy : 0.918
Model ke simpan ke random_forest_classifier.joblib

📊 RUSBoost Classifier
Accuracy : 0.925
Model ke simpan ke rusboost_classifier.joblib

📊 Logistic Regression
Accuracy : 0.964
Model ke simpan ke logistic_regression.joblib

📊 Gradient Boosting Classifier
Accuracy : 0.937
Model ke simpan ke gradient_boosting_classifier.joblib

📊 Balanced Random Forest Classifier
Accuracy : 0.895
Model ke simpan ke balanced_random_forest_classifier.joblib